### PR TITLE
Adding Support for Home Folder Path

### PR DESCRIPTION
**Pull request by groomsy**
Added support for home folder path for keychain (~/). I also do not think the unlock keychain command was being called properly (I noticed it was calling it without the keychain specified, but this may have been from my change to add support for the home folder path). I also added the keychain flag to the certtool commands.

### CODE REVIEW

**Comment by MartinMReed** [comment]
I'm leaving out the KeychainHelper and just moving it to InitializeMojo+XcodeService.

Also, I changed it so if there is no Keychain.keychain specified, it will look up what the default keychain is... so there will always be a keychain path if any keychain info is specified in the pom.

**Comment by MartinMReed** [comment]
Okay, these changes are working fine for me. Thought I had an issue with the k=keychain on the certtool... but my cert just expired and caused weird issues trying to install it.

Thanks Todd!

**Comment by groomsy** [comment]
I'm glad these worked. I had initially created the KeychainHelper to have a centralized method for building the keychain path, among others, because I initially wasn't sure where I would need everything. I think it makes sense to have it in the InitializeMojo+XcodeService (I'm still grasping Mojos, for whatever reason, these seem foreign to me).

Is there anyway to check for certificate expiration to give a better error message?

**Comment by MartinMReed** [comment]
Yea. You can print the certificate info and use regex to pull out the expiration date.

certtool d developer.cer

Which will print the validity dates:

Not Before         : 18:15:29 Dec 16, 2011
Not After          : 18:15:29 Dec 15, 2012

**Pull request closed without merging**
