### PR TITLE
Use CODESIGN_ALLOCATE Bash Var if Available

### PR DESCRIPTION
**Pull request by groomsy**
I made an update so that it checks for the CODESIGN_ALLOCATE bash variable before hard-coding the environment variable. It'll set the environment variable to the preset bash variable if it exists. This may be unnecessary, but I wanted to set it to be sure.

When I tried running your build tool on my Mac, it's using the BourneShell from the plexus-utils project. The BourneShell single quote escapes anything with a pipe or dollar sign in it by default. I copied the BourneShell and modified it in my fork of hbc-maven-core. My fork of hbc-maven-core now uses this new shell (named HBCShell) which doesn't single quote escape pipes or dollar signs. Truthfully, I'm not sure how it ever worked before.

EDIT: You may have to pick my changes; I had forked the metova fork, but I wanted you to have my changes if you wanted them.

### CODE REVIEW

**Comment by MartinMReed** [comment]
Yea I'm seeing the single quote also. It's new to Mountain Lion... wasn't there on Snow Leopard, or if it was it didn't error.

**Comment by MartinMReed** [comment]
If all you changed are the quoting characters, you could just extend BourneShell and override getQuotingTriggerChars.

I'm adding org.hardisonbrewing.maven.core.cli.BourneShell that just overrides getQuotingTriggerChars with your same chars.

**Comment by MartinMReed** [comment]
Rather than doing an echo on $CODESIGN_ALLOCATE I added a check to see if its already added to the Commandline. The Commandline should pull in what you already have in your .bash_profile, so theres no need to add it again.

I also made it so if its not already added, first it will call 'which codesign_allocate' since it could already be in your path. For me its already available at /usr/bin/codesign_allocate. Then it will check the XCode 4.5 path, then the 4.3 path... or throw an error saying to add it to the env vars.

**Comment by MartinMReed** [comment]
Those are merged now. Already had the flex changes.

**Comment by groomsy** [comment]
Great changes. Glad I could contribute. I should have extended the BourneShell, but I was in a rage fit towards the end and just wanted to finish it.

**Pull request closed without merging**
